### ISSUE TITLE
Naming del icono de examen oficial

### ISSUE THREAD

**Issue by dlorenzonespereira** [opositatest/design-tokens#32]
Para el icono exam-type/exam-official.svg, el tipo "official" no se corresponde con el tipo de examen en la base de datos, que se nombra como "oficial", por lo que hay que convertir el string cuando se usa. Ver si compensa renombrarlo o corregirlo en base de datos para evitar esta conversión

**Comment by dlorenzonespereira** [comment]
Creo que de momento es más costoso el cambio que dejarlo como está, ya que todos los proyectos ya hacen la comprobación

**Comment by barcia** [comment]
El nombre está correctamente en inglés.
